version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - dbData:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadminData:/var/lib/pgadmin
    ports:
      - '16543:80'
    depends_on:
      - postgres-compose
    networks:
      - postgres-network

volumes:
  dbData:
  pgadminData:

networks:
  postgres-network:
    driver: bridge
